name: coding-workspace
services:
  ubuntu:
    container_name: ubuntu
    build: .
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    volumes:
     - ./docker-files:/home/docker-files